//! Core data types for the self-improvement subsystem.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Task description (discovered from disk)
// ---------------------------------------------------------------------------

/// Metadata for one benchmark task discovered from the `tasks/` directory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskDescriptor {
    /// Short slug (e.g. `"example-task"`).
    pub name: String,
    /// Human-readable description from `task.toml`.
    pub description: String,
    /// Per-task timeout in seconds.
    pub timeout_secs: u64,
    /// Absolute path to the task directory.
    pub path: PathBuf,
    /// Contents of `instruction.md` (empty string if absent).
    pub instruction: String,
}

// ---------------------------------------------------------------------------
// Task result (produced by running a task)
// ---------------------------------------------------------------------------

/// Outcome of executing a single benchmark task.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskResult {
    pub name: String,
    pub passed: bool,
    /// Normalised score in `[0.0, 1.0]`.
    pub score: f64,
    /// Combined stdout + stderr output (truncated if very long).
    pub output: String,
    /// Wall-clock duration in seconds.
    pub duration_secs: f64,
    /// Absolute path to the task directory (needed by `MetaAgent`).
    pub task_dir: PathBuf,
}

// ---------------------------------------------------------------------------
// Proposal (generated by MetaAgent, applied to disk)
// ---------------------------------------------------------------------------

/// A concrete file change proposed by the `MetaAgent`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Proposal {
    /// Filename to write, relative to `task_dir` (e.g. `"solution.py"`).
    pub file: String,
    /// Human-readable description of the change.
    pub description: String,
    /// Full content to write verbatim.
    pub content: String,
    /// Name of the task this targets (for logging / tracing).
    pub task_name: String,
    /// Absolute path to the task directory.
    /// `None` → `file` is treated as a project-relative absolute path.
    pub task_dir: Option<PathBuf>,
}

impl Proposal {
    /// Return the absolute path where the file should be written.
    #[must_use]
    pub fn resolve_path(&self) -> PathBuf {
        match &self.task_dir {
            Some(dir) => dir.join(&self.file),
            None => PathBuf::from(&self.file),
        }
    }

    /// Returns `true` if this is a no-op placeholder (empty content, no
    /// task dir).  Placeholders are logged but not written to disk.
    #[must_use]
    pub fn is_placeholder(&self) -> bool {
        self.task_dir.is_none() && self.content.trim().is_empty()
    }
}

// ---------------------------------------------------------------------------
// Score-history row
// ---------------------------------------------------------------------------

/// One row in the `results.tsv` log.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScoreEntry {
    pub timestamp: String,
    pub commit: String,
    pub avg_score: f64,
    pub passed: usize,
    pub total: usize,
    pub status: String,
    pub description: String,
}

// ---------------------------------------------------------------------------
// Iteration result (returned by ExperimentLoop::run)
// ---------------------------------------------------------------------------

/// Summary of a single hill-climbing iteration.
#[derive(Debug, Clone)]
pub struct IterationResult {
    pub iteration: usize,
    pub commit: String,
    pub avg_score: f64,
    pub passed: usize,
    pub total: usize,
    /// `true` → changes were kept (score improved); `false` → reverted.
    pub kept: bool,
    pub description: String,
}
